version: '3'

services:
  doctor_crud_database:
    image: postgres
    container_name: doctor_crud_database
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=academy
      - POSTGRES_PASSWORD=gcb123
      - POSTGRES_DB=doctor_crud_database
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: doctor-crud
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - doctor_crud_database
    depends_on:
      - doctor_crud_database

volumes:
  pgdata:
